game:
  time: 200 # int, MAX: 255

pickups:
  coin: 2    # int
  carrot: 25  # int
  light_ammo: 100   # int
  heavy_ammo: 25    # int
  power_ammo: 10    # int

bullets:
  normal: 
    max_ammo: 255 #cantidad maxima 255 
    speed: 1.0
    damage: 15
    bpm: 500
  light: 
    max_ammo: 250
    speed: 1.0
    damage: 10
    bpm: 1000
  heavy: 
    max_ammo: 250
    speed: 1.0
    damage: 40
    bpm: 250
  power: 
    max_ammo: 250
    speed: 1.0
    damage: 100
    bpm: 100

enemy: 
  flyer:                                        # el rápido
    count: 10  # int
    life: 10   # int
    speed: 0.4  # float
    damage: 40 # int
  shooter:                                      # el normal
    count: 10  # int
    life: 100   # int
    speed: 0.25  # float
    damage: 20 # int
  crawler:                                      # el tanque
    count: 10  # int
    life: 200   # int
    speed: 0.07  # float
    damage: 40 # int
  

player: 
  speed: 0.25       # float
  jump: 1        # int
  max_healh: 100 # int
